export default function Profile({profileData,setProfileData}){
    return(
        <>
        <h1>Profile</h1>
        <h2>Name: 
            <input 
            onChange={(e)=>{
                setProfileData(prevData=>
                    ({
                    ...prevData,
                    name:e.target.value
                }))
            }}
            value={profileData.name}/>
            </h2>
        <h2>Email: 
        <input 
            onChange={(e)=>{
                setProfileData(prevData=>
                    ({
                    ...prevData,
                    email:e.target.value
                }))
            }}
            value={profileData.email}/>
        </h2>
        <h2>Age: 
        <input 
            onChange={(e)=>{
                setProfileData(prevData=>
                    ({
                    ...prevData,
                    age:e.target.value
                }))
            }}
            value={profileData.age}/>
        </h2>
        </>
    )
}